### ISSUE TITLE
data file upload - give it a name?

### ISSUE THREAD

**Issue by julie-sullivan** [yochannah/wizard-api-specs#14]
each data source in InterMine has a data set (and data source name). e.g. UniProt, BioGRID

Would we like people to give their data set a name? Make it optional? Use the filename as default?

Or should `intermine-creator` make up a data source name, e.g. `mySource1`

It matters a lot less since there will only be one data source. but might be useful to separate their data from the supp data. 

Just a thought!

**Comment by yochannah** [comment]
I think we should leave the number of inputs to a complete minimum on the wizard, and auto-generate the name of the data source, perhaps from the filename and other specs like organism and/or column mappings. 

The wizard UI is going to be very complex as it is!
