### ISSUE TITLE
How do we want to pass files around?

### ISSUE THREAD

**Issue by julie-sullivan** [yochannah/wizard-api-specs#16]
https://stackoverflow.com/questions/4083702/posting-a-file-and-associated-data-to-a-restful-webservice-preferably-as-json

I am going to do base64 for now because it's the easiest. Will this cause performance issues?

**Comment by yochannah** [comment]
I'm not loving this bit (emphasis mine):

>Base64 encode the file, at the expense of increasing the data size by around 33%, and add processing overhead in both the server and the _client_ for encoding/decoding.

I don't know what performance will be for base64 encoding a file on the client but it might mean people with lower-powered computers can't upload medium or large files. I'm going to copy/paste some code from SO into a tiny prototype and test it on one of our macbook airs to see if it calms me or frightens me.

**Comment by yochannah** [comment]
yep, this *will* be a problem for larger files. 

You can try yourself here: https://yochannah.github.io/base64encoder-performance-checker/

open the console to see the time taken to encode the file. We take a time stamp before we start encoding and again after. On Arctic tern (a 2011 13 inch macbook air with 4GB of RAM and a intel i7 1.8 GHz processor), a 660mb file takes 40 seconds to encode and the screen becomes white and unusable for the duration. My dev machine takes around 10 seconds for a similar file, which honestly is still long enough to make someone bored and wander off. 

We might be able to make the performance nicer using web workers, but if we're going to spend extra time on performance it might be better to go for the multipart data.

**Comment by julie-sullivan** [comment]
Yes, that's what I understood from the stackoverflow post comments. Probably best to do things correctly from the start I suppose.

How does this impact the API end points? As there can be several files, and associated InterMine metadata.

**Comment by julie-sullivan** [comment]
For the wizard -- instead of `/file/properties/detect/`, we should post the file first, then use that file ID to send the metadata

```
# for intermine_wizard

POST /file/submit 
// returns FILE_ID

GET /file/properties/detect/<FILE_ID>

```

For intermine-compose, we shouldn't include the files in the CONFIG. Instead, we should return the list of files, which are retrieved separately.

```
# for intermine_compose

GET /mine/config/<MINE_ID>
// returns a list of <FILE_ID>s

GET /file/retrieve/<FILE_ID>
// returns the file associated with that ID

```


Thoughts?

If this looks vaguely correct, then I'll update the end points.

**Comment by julie-sullivan** [comment]
https://galaxyproject.org/ftp-upload/ -- see how galaxy handles files.

Also did we want a new end point that takes URLs

**Comment by julie-sullivan** [comment]
Solved! Going to use Amazon Elastic File System to store files, and just pass around the FILE_ID.

The dashboard will have to handle big file uploads though. Somehow.
